name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-check:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Rust Cargo cache
      uses: raviqqe/cargo-cache@v1
    - name: Build
      run: cargo build -q
    - name: Check
      run: cargo check -q
